apiVersion: v2
name: smarthome
description: A Helm chart for the Smart Home application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kafka
    version: 30.1.4
    repository: oci://registry-1.docker.io/bitnamicharts