apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
  labels:
    app: device-service
spec:
  replicas: {{ .Values.deviceService.replicaCount }}
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
        - name: device-service
          image: {{ .Values.deviceService.image.repository }}:{{ .Values.deviceService.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deviceService.service.port }}
          env:
            - name: NODE_ENV
              value: "{{ .Values.deviceService.env.NODE_ENV }}"
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.primary.service.port }}"
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.global.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.global.postgresqlPassword }}
      
---
apiVersion: v1
kind: Service
metadata:
  name: device-service
spec:
  selector:
    app: device-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.deviceService.service.port }}
  type: {{ .Values.deviceService.service.type }}