apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service
  labels:
    app: telemetry-service
spec:
  replicas: {{ .Values.telemetryService.replicaCount }}
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
        - name: telemetry-service
          image: {{ .Values.telemetryService.image.repository }}:{{ .Values.telemetryService.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.telemetryService.service.port }}
          env:
            - name: NODE_ENV
              value: "{{ .Values.telemetryService.env.NODE_ENV }}"
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.primary.service.port }}"
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.global.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.global.postgresqlPassword }}
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
spec:
  selector:
    app: telemetry-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.telemetryService.service.port }}
  type: {{ .Values.telemetryService.service.type }}