apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.kafka.zookeeper.image }}:{{ .Values.kafka.zookeeper.tag }}
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 2181
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.kafka.image }}:{{ .Values.kafka.kafka.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.kafka.kafka.servicePort }}
          env:
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:{{ .Values.kafka.kafka.servicePort }}
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:{{ .Values.kafka.kafka.servicePort }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.kafka.kafka.zookeeperConnect }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: {{ .Values.kafka.kafka.servicePort }}
  clusterIP: None
  selector:
    app: kafka