name: Build and Push Docker Images

on:
  push:
    branches:
      - sprint_3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository owner to lowercase
        id: vars
        run: echo "::set-output name=owner::${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'

      - name: Build and push deviceService image
        uses: docker/build-push-action@v4
        with:
          context: ./solution/services/deviceService
          file: ./solution/services/deviceService/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/device-service:latest

      - name: Build and push telemetryService image
        uses: docker/build-push-action@v4
        with:
          context: ./solution/services/telemetryService
          file: ./solution/services/telemetryService/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/telemetry-service:latest
